language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get install graphviz
  - pwd
  - pip install future requests pygraphviz bel_resources
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install functools32;
    fi
  - git clone https://github.com/sorgerlab/indra.git
script:
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/indra
#  - python check_references.py
#  - python export/relations_graph.py
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip install bel_resources;
      python export/obo.py;
      python export/hgnc_ids.py;
      python export/belns.py;
      belns_diff=$(git diff -U0 export/famplex.belns | egrep "^[\+-][^\+-]");
      echo $belns_diff;
      belns=$(echo "$belns_diff" | egrep -v
      "^[\+-](VersionString|CreatedDateTime)");
      echo $belns;
      obo_diff=$(git diff -U0 export/famplex.obo | egrep "^[\+-][^\+-]");
      echo $obo_diff
      obo=$(echo "$obo_diff" | egrep -v "^[\+-]date");
      echo $obo;
      hgnc=$(git diff -U0 export/hgnc_symbol_map.csv | egrep "^[\+-][^\+-]");
      if [[ ! -z $belns ]] || [[ ! -z $obo ]] || [[ ! -z $hgnc ]]; then
        echo "Exports have not been updated";
        exit 1;
      fi
    fi
