language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install graphviz
  - pwd
  - pip install future requests pygraphviz bel_resources
  - git clone https://github.com/sorgerlab/indra.git
script:
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/indra
  - python famplex/check_references.py
  - python famplex/export/export_relations_graph.py
  # test if exports have been updated
  # bel_resources must be installed to generate belns exports
  # generate exports then take git diff and look only at lines that changed
  # lines containing date, timestamp, or version should be ignored
  - python famplex/export/export_obo.py
  - python famplex/export/hgnc_ids.py
  - python famplex/export/export_belns.py
  - export belns_diff=$(git diff -U0 export/famplex.belns | egrep "^[\+-][^\+-]")
  - export belns=$(echo "$belns_diff" | egrep -v "^[\+-](VersionString|CreatedDateTime)")
  - export obo_diff=$(git diff -U0 export/famplex.obo | egrep "^[\+-][^\+-]")
  - export obo=$(echo "$obo_diff" | egrep -v "^[\+-]date")
  - export hgnc=$(git diff -U0 export/hgnc_symbol_map.csv | egrep "^[\+-][^\+-]")
  - if [[ ! -z $belns ]] || [[ ! -z $obo ]] || [[ ! -z $hgnc ]]; then
      echo "FAIL exports have not been updated";
      exit 1;
    fi
